# Generated by Django 5.2 on 2025-04-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Remote", "Remote"),
                ],
                default="Absent",
                max_length=10,
            ),
        ),
    ]
