# Generated by Django 5.2 on 2025-04-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_projectassignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="employee",
        ),
    ]
